Feature homepage&header
CPG-Innovation-Team/cpg-innovation-team-website pull request #13
Opened 2021-07-02 03:08 UTC by lmy0125

对navbar进行移动设配的适配；
为首页内容创建了中英文文档，可进行中英文切换；
使用了实际图片及文案进行填充；
使用了for-loop增加可读性。

2021-07-02 07:50 UTC, casualbill requested changes
1. 图片文件命名可以参照 README.md 中的相关规则
2. 语言文件的命名可以参照国际通用的语言-地区代码表，比如简体中文可以用 zh-cn，以示与港、台繁体的区别
3. 既然做了 i18n 多语言支持，不妨考虑下如果还需要其他语言是否方便扩展

2021-07-02 07:50 UTC, casualbill commented on .prettierrc.js
> +  arrowParens: 'always',
通常修改 ESLint 或 Prettier 的规则配置最好可以团队达成一致，所以这边你加上这条是有遇到什么问题了吗？

2021-07-04 19:26 UTC, lmy0125 commented on .prettierrc.js
> +  arrowParens: 'always',
这个是我做coding test时不小心改错文件了，不好意思。

2021-07-04 19:28 UTC, lmy0125 commented
第三点的话具体时间什么意思？怎么样的形式可以算是方便扩展？

2021-07-05 03:23 UTC, casualbill commented
方便扩展：以最小的代价（改动）加入一个新的语言
比如你的方法是 changeToCN, changeToEN 如果新写一个语言就需要再多一个方法，是否可以封装起来呢？

2021-07-05 03:25 UTC, casualbill commented
还有些问题。。prettier你上次多加了个规则，这次又删掉了些规则-.-
恢复了重新格式化一下吧

另外图片的命名规则里建议用 jpg 而非 jpeg 作为扩展名

2021-07-05 03:36 UTC, casualbill commented
建议在提交前通过工具或者 git diff 重新检查一下修改的内容

2021-07-05 21:43 UTC, lmy0125 commented
不好意思没有仔细阅读README。我把prettier改回去后有要求singleQuote: true, 但是 eslint 有warning要求用double quote。这个问题之前没有，不知道是什么原因。

2021-07-06 02:08 UTC, casualbill commented
> 不好意思没有仔细阅读README。我把prettier改回去后有要求singleQuote: true, 但是 eslint 有warning要求用double quote。这个问题之前没有，不知道是什么原因。

试试看在 VSCode 安装 prettier 插件
参考文档：[前端代码编辑器配置说明](https://s80qad06mf.feishu.cn/docs/doccn70aCrLbeQ4CaUCeFOnaxTb)

2021-07-06 06:24 UTC, casualbill requested changes

2021-07-06 06:24 UTC, casualbill commented on src/components/HeaderNav.vue
> +  </div>
最外层的 div 是否是必要的呢？直接用标签 v-navigation-drawer 会有问题吗？
如果一样的话建议去掉 div 以减少标签嵌套层级（有利于性能）

2021-07-06 06:24 UTC, casualbill commented on src/plugins/vue-i18n.js
> +});
这个 JS 文件格式还是有点问题，都是双引号。。

2021-07-06 06:24 UTC, casualbill commented on tests/unit/HeaderNav.spec.js
> +});
单元测试的意义在于保证所有 script 中的脚本路径有符合预期的实现，尤其是方法。。。这个组件连 props 都没有，就不用按官方的 HelloWorld 去照葫芦画瓢了>_<

2021-07-06 06:27 UTC, lmy0125 commented on src/components/HeaderNav.vue
> +  </div>
这个是因为template只能有一个tag，这个div 里面有两个物件

2021-07-06 06:28 UTC, lmy0125 commented on tests/unit/HeaderNav.spec.js
> +});
ok，我刚开始就先把他的抄过来了

2021-07-06 06:28 UTC, lmy0125 commented on src/components/HeaderNav.vue
> +  </div>
这样的话还需要把它合成一个吗

2021-07-06 06:52 UTC, casualbill commented on src/components/HeaderNav.vue
> +  </div>
哦好，那就保持这样。。是我看得不够仔细@_@

2021-07-06 06:53 UTC, casualbill commented
还有一个图片的命名参照一下规范，img-cp-logo.png 差不多这样就ok

2021-07-06 06:54 UTC, casualbill commented on tests/unit/HeaderNav.spec.js
> +});
我把 HelloWorld 去掉了，Vue-cli 产生的一个起始模板，参考用的

2021-07-06 06:55 UTC, casualbill commented on tests/unit/HeaderNav.spec.js
> +});
你这个文件先不要提交了，之后写正经的单元测试哈

2021-07-07 07:22 UTC, casualbill approved these changes

2021-07-07 07:46 UTC, merged