admin blog: support password modification, improve page layout
CPG-Innovation-Team/cpg-innovation-team-website pull request #45
Opened 2021-11-25 18:32 UTC by fork1028

* 修改密码api
* tag属性改为dropdown
* blog首页增加翻页、按like排序
* admin blog页面增加基础搜索

2021-11-29 09:36 UTC, casualbill requested changes

2021-11-29 09:36 UTC, casualbill commented on src/views/admin/ApproveBlog.vue
> +        console.log(Number.MAX_SAFE_INTEGER);
测试通过后建议移除log

2021-11-29 09:36 UTC, casualbill commented on src/views/admin/ApproveBlog.vue
>              },
现在所有登录后的接口都要带 token，那建议把接口封装起来，省得每个接口都重复写 header和token属性

2021-11-29 09:36 UTC, casualbill commented on src/views/admin/ApproveBlog.vue
>              },
token数据也可以保存在更上层级的组件中

2021-11-29 09:37 UTC, casualbill commented
单元测试是在另外的分支单独提PR吗？

2021-11-30 19:33 UTC, fork1028 commented
> 单元测试是在另外的分支单独提PR吗？

嗯嗯我另外建了个分支，等会提一下

2021-11-30 19:34 UTC, fork1028 commented on src/views/admin/ApproveBlog.vue
>              },
> 

好的

2021-12-06 09:32 UTC, merged