fix blog bugs & add international locale support for login/signup/blog
CPG-Innovation-Team/cpg-innovation-team-website pull request #65
Opened 2022-03-24 20:21 UTC by fork1028

* 博客页面显示作者头像+昵称
* 注册添加前端校验
* 修改公告未正确显示bug
* 博客、登录、注册页面增加国际化支持
* 增加最受欢迎博客接口
* 博客列表封面添加默认封面
* 用户头像添加默认头像
* 博客详情页面封面更改为博客封面图片
* admin移除activity
* 修改未登录用户无法正常获取博客信息bug
* 修改登录跳转返GET 403 error

2022-03-25 07:33 UTC, casualbill requested changes

2022-03-25 07:33 UTC, casualbill commented on src/views/admin/Announcement.vue
> +              beginTime: (Date.parse(`${this.startDate} ${this.startTime}:00`) / 1000).toString(),
项目已经引入了 moment.js，可以尝试用其方法来解析时间

2022-03-25 07:33 UTC, casualbill commented on src/views/admin/Blogs.vue
> +a {
一般来讲除非全局应用，不建议采用标签来定义样式，用class会更好

2022-03-25 07:33 UTC, casualbill commented on src/views/admin/Blogs.vue
> +a {
因为浏览器渲染解析标签是先找所有的该标签，再根据条件来选择，如果标签多的话可能会有性能上的问题

2022-03-25 07:34 UTC, casualbill commented
改差不多了直接合staging好了，测过以后再合master

2022-03-26 01:09 UTC, fork1028 commented
> 改差不多了直接合staging好了，测过以后再合master

好的

2022-03-27 16:25 UTC, merged